### ISSUE TITLE
[FEATURE] Update filter by profile types

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/LinkFree#1105]
### Description

The 3 filter options in order under profile types are as follows:

Personal
All
Community

According to me, it will be better if it's in the following order:
Personal
Community
All

or

Community
Personal
All

Preferably, the first one.

**Comment by emmalearnscode** [comment]
I was thinking this was a duplicate but couldn’t find another issue like it. Then I realised I wrote it in my notepad and never wrote it up here. I think they should be in alphabetical order and that would work well since ALL is the default anyway.

**Comment by KendallDoesCoding** [comment]
> I was thinking this was a duplicate but couldn’t find another issue like it. Then I realised I wrote it in my notepad and never wrote it up here. I think they should be in alphabetical order and that would work well since ALL is the default anyway.

According to me, My suggestions are the best, but even in alphabetical order is the next best thing, better than it is now, so we can proceed!

**Comment by KendallDoesCoding** [comment]
> > My suggestions are the best
> 
> @KendallDoesCoding LOL 😂 actually collaboration is best 😉

Lol, that sounds funny but what I meant to say was, according to me my suggestions look good, but we can do it in alphabetical order, I'm a new coder and would never say
> My suggestions are the best 
:
Personal
Community
All

or

Community
Personal
All

**Comment by eddiejaoude** [comment]
But you did say that, and that was my point. It is not what you say, it is how you say it. I recomend focusing on collaboration first rather than pushing your personal preferences, as we are seeing this a lot from you. Please think and re-read before you send your messages as they can offend other people in the community.

**Comment by KendallDoesCoding** [comment]
> But you did say that, and that was my point. It is not what you say, it is how you say it. I recomend focusing on collaboration first rather than pushing your personal preferences, as we are seeing this a lot from you. Please think and re-read before you send your messages as they can offend other people in the community.

Yes. that's totally my mistake. Really sorry for that.

**Comment by Vyvy-vi** [comment]
I think an order with "All" at the bottom would be undesirable since it's the default setting. It makes sense to keep the default option at the top, as stated by emmalearnscode.

From the above discussion, it looks like the order proposed by @KendallDoesCoding isn't wanted right now.
Moreover, there's also a  lack of reasoning behind why that order is needed, besides it stated as "the best".
This coupled with the discussion doesn't allow contributors to clearly interpret the issue(and make the needed changes, which were suggested by Emma). 

We're closing this issue for now, but feel free to reopen the issue or open a new one, if you have any reasoning to add.

**Comment by KendallDoesCoding** [comment]
> I think an order with "All" at the bottom would be undesirable since it's the default setting. It makes sense to keep the default option at the top, as stated by emmalearnscode.
> 
> From the above discussion, it looks like the order proposed by @KendallDoesCoding isn't wanted right now. Moreover, there's also a lack of reasoning behind why that order is needed, besides it stated as "the best". This coupled with the discussion doesn't allow contributors to clearly interpret the issue(and make the needed changes, which were suggested by Emma).
> 
> We're closing this issue for now, but feel free to reopen the issue or open a new one, if you have any reasoning to add.

I think it will be better, if the order is

"Personal"
"Community"
"All"

cause, it makes it easier for the user to tap just the next one, all will automatically open, but I do think it will be better with this format, but if this isn't a valid reasoning, then feel free to not inculde :), it was just a suggestion.
