### ISSUE TITLE
[FEATURE] Allow creating LinkFree instances for single person

### ISSUE THREAD

**Issue by Pierstoval** [EddieHubCommunity/LinkFree#1197]
### Description

For now, if you want to host LinkFree, you have to host the whole profiles database.

If you want to host only an instance for yourself (like I did there this morning for testing purposes: https://links.piers.tech/pierstoval), you will have to remove the rest of the database.

I haven't digged into the code source yet, but would it be possible to add a switch somewhere to specify the **only** profile we would want to see?

It would need these changes:
* Disable `/{profile}/` route
* Make `/` route show the configured profile
* Remove the `⬅` link on the top left of the site
* Since this is for self-hosting purposes, the `Share` links must be updated too to use the current domain instead of `linkfree.eddiehub.org`

WDYT?

**Comment by Vyvy-vi** [comment]
While it would be really neat to have self-hosted instances for LinkFree, that might divulge from our project goal - "Link-sharing pages for community member discovery". Somewhere down the line, this would be linked with our community API and our discord bot, which might make setting up user-specific instances slightly complex.

However, if you're interested in setting up a personal instance, feel free to fork the project and tweak it with the changes above. Moreover, there are many user-specific linkfree-like(linktree-like) projects out there. (this might also be more beneficial since you could have more custom styling this way)

**Comment by Vyvy-vi** [comment]
One thing we could look into is -
Making a fork of LinkFree or a branch on Linkfree that's user-specific (for single users)

**Comment by Pierstoval** [comment]
I will try this out during a live-stream next wednesday then 👍

**Comment by Pierstoval** [comment]
@Vyvy-vi Done in #1207, please check it out if you're interested in a cross-compatible way that keeps the original behavior whenever nothing is done 😉
