### ISSUE TITLE
The links in the profile section of the user do not redirect to next page.

### ISSUE THREAD

**Issue by Kanika637** [EddieHubCommunity/LinkFree#1378]
### Description

The social links in the profile section of the user in LinkFree do not redirect to a new page, they open in the same page.

### Screenshots

![2e](https://user-images.githubusercontent.com/84350895/173184471-bd821fe3-90fe-4a4c-9ed7-1637d6ecfbf0.png)
![1e](https://user-images.githubusercontent.com/84350895/173184474-7219037e-4984-43fc-a296-09a3a4e575ce.png)

**Comment by KarlGusta** [comment]
Opening on a new tab is a good idea. If the maintainers are okay, I can work on it with their blessings.

**Comment by emmalearnscode** [comment]
> Opening on a new tab is a good idea. If the maintainers are okay, I can work on it with their blessings.

It's actually best practise and better for accessibility not to open links in new tabs/windows unless it causes the user to lose something they're already doing eg filling in a form. This is because not everyone can see that a new tab/window has opened and screen readers don't automatically announce that a new tab/window has been opened which can lead to  confusion about which tab is open and the browsing history may not be as expected. Therefore, I would not suggest we make this change.

**Comment by KarlGusta** [comment]
As an advocate of a11y, this is great advice Emma. I didn't know it before.

**Comment by emmalearnscode** [comment]
I'll close this and the associated pull request since it's more accessible to leave them as they currently are.
