### ISSUE TITLE
(feat): Add the profile in the app itself 

### ISSUE THREAD

**Issue by 87prashant** [EddieHubCommunity/LinkFree#1500]
#### (Not sure about the feasibility)
We can add the feature of adding a new profile in the application itself through some form rather than adding profile through the  `username.json`

It would be very easy to add the profile then.

**Comment by Arushay** [comment]
Yeah it can be possible but I think its better if we leave it like that at least beginners are learning "basics" like 
How to contribute?
How to write a good json file?
How to make a good pull request?
How to use Git?

**Comment by kumarsonsoff3** [comment]
**I'm 100% agreed with @Arushay, our main motto for this project is to help out people to get started with open-source.** 
In the complete process, many beginners learn a lot including the points **Arushay** mentioned. 

Apart from all these, If we do so, then we'll have to add authentication to the web app so that no one can edit others' data, because there will be no role of maintainers. 
It will be like **linktree** then, and will have nothing to do with GitHub. Isn't it!?

**Comment by EmmaDawsonDev** [comment]
I think there are plans to add a backend eventually and then this will be feasible. But the way it works now allows people to practice the whole git flow from forking cloning to making a pull request without having to make massive changes so it’s a great learning opportunity.
