### ISSUE TITLE
[FEATURE] Add Dark Mode

### ISSUE THREAD

**Issue by Keshraf** [EddieHubCommunity/LinkFree#1838]
### Description

EddieHub is a community of developers and open-source enthusiasts. And who doesn't love dark mode more than them? I would like to add dark mode support. 

Please assign this issue to me and attach the Hackoberfest label.

### Additional information

🌚

**Comment by vasucp1207** [comment]
Hey, @Keshraf I am looking to work on this but can you please tell me which place on the home page, I will add the toggle for the theme switch because we have to adjust the header if we implement this on the home page.

<img width="1440" alt="Screenshot 2022-10-01 at 1 28 17 PM" src="https://user-images.githubusercontent.com/85363195/193399487-48724755-949d-4ad5-a37e-d7ce30882c03.png">

**Comment by Keshraf** [comment]
Hey @vasucp1207, actually I added this issue as I wanted to work on it. I am waiting for a maintainer to assign this issue to me. You can create more issues and work on them instead

**Comment by krshkodes** [comment]
We would want it on the navbar, also we need to look up media queries as well

**Comment by vasucp1207** [comment]
Sorry, @Keshraf I do not read the full description.

**Comment by Keshraf** [comment]
> Sorry, @Keshraf I do not read the full description.

Not a problem. Don't worry about it. There are a lot more things you contribute to!

**Comment by EmmaDawsonDev** [comment]
Sure @Keshraf go ahead. Please make this addition to the next-js branch instead of the current main branch so that it will be included in v2 of linkfree

**Comment by Keshraf** [comment]
Okay understood. Thank you for letting me know!

**Comment by Vedant-Manjrekar** [comment]
Hey actually i have worked on this issue already, as it was raised earlier as well, so if @Keshraf is not able to implement this feature i can help, just do let me know.

**Comment by EmmaDawsonDev** [comment]
> Hey actually i have worked on this issue already, as it was raised earlier as well, so if @Keshraf is not able to implement this feature i can help, just do let me know.

Oh sorry, I didn't know someone was already working on this. What's the issue number?

**Comment by Vedant-Manjrekar** [comment]
> > Hey actually i have worked on this issue already, as it was raised earlier as well, so if @Keshraf is not able to implement this feature i can help, just do let me know.
> 
> Oh sorry, I didn't know someone was already working on this. What's the issue number?

It's #1032

**Comment by EmmaDawsonDev** [comment]
Ok, this is a bit difficult since the issue was never assigned and the last message is from august so it looks abandoned but we can do like this. 

Vedant - make your PR to the main branch as it looks like you made yours in prime react (no need to ask to make a PR)
Keshraf - make a version for the next-js branch instead.

hope that works for everyone

**Comment by Keshraf** [comment]
That works for me!

**Comment by Vedant-Manjrekar** [comment]
Works for me as well.

**Comment by ManishBisht777** [comment]
Hi is this issue worked upon?

**Comment by ManishBisht777** [comment]
there is  issue opened similar to this #2957 
I want to work on this if @Keshraf is not working on this

**Comment by SaraJaoude** [comment]
Thank you for raising this idea, but I will be closing this issue as #2957 deals with the same subject and has more discussions.
