### ISSUE TITLE
[FEATURE] Login in with OAuth

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2176]
### Description

Ideas after authenticated:
- Login to see your stats

**Comment by nanthakumaran-s** [comment]
Sounds great. Can I also work on this issue?

**Comment by ChinmayMhatre** [comment]
Hey @eddiejaoude , I was wondering. Since the goal of having PRs to create the profile was to encourage people to learn how to contribute to open source. Doesn't having an online form to do that go against this?

I feel having the PR system has led to a lot more contributors as they see that oh I can contribute this easily and then tend to then go do reviews, create issues and much more.

Was wondering what your thoughts are on this?

**Comment by ChinmayMhatre** [comment]
Hey @eddiejaoude , I was wondering. Since the goal of having PRs to create the profile was to encourage people to learn how to contribute to open source. Doesn't having an online form to do that go against this?

I feel having the PR system has led to a lot more contributors as they see that oh I can contribute this easily and then tend to then go do reviews, create issues and much more.

Was wondering what your thoughts are on this?🤔

**Comment by eddiejaoude** [comment]
This has been done
