### ISSUE TITLE
Responsiveness - Profile page

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#2465]
### Description

I am checking the responsive in 320px width

The profile image on the profile page looks odd in the mobile view
![image](https://user-images.githubusercontent.com/89926834/209342485-8f15b758-c9ae-4325-b58b-cbae8fa3d0c5.png)

we can change the layout to this to prevent the name of wrapping and also saving to image from being distorted
![image](https://user-images.githubusercontent.com/89926834/209342212-06777a95-12de-4344-acde-96af3cfe6360.png)

**Comment by Aadarsh805** [comment]
This is happening because the profile picture and name are in flex and items-stretch, if we switch it to items-center the picture will not lose its aspect ratio but it will still sharing, like this:
> Left(before) right (after)
![image](https://user-images.githubusercontent.com/95094057/209565044-28ed9d69-26a4-4b51-becb-26cb31bb2645.png)

**Comment by Aadarsh805** [comment]
Instead of changing the layout, this can fix it

**Comment by stephenokyere233** [comment]
@eddiejaoude could you assign this to me?

**Comment by eddiejaoude** [comment]
Thank you @ManishBisht777 for raising the issue 👍 and thank you @Aadarsh805 for the solutions - both are good solutions

@stephenokyere233 it is assigned to you as requested

**Comment by stephenokyere233** [comment]
Thanks for assigning me @eddiejaoude
