### ISSUE TITLE
[FEATURE] Popular profile page to also show new users

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#2542]
### Description

I think the popular profiles don't change so much, so it would be great to also show new profiles

These can be displayed under the popular profiles and the page could be renamed to `Featured Profiles`

**Comment by adityassharma-ss** [comment]
hey @eddiejaoude,
I will be working on this, please assign it to me.

**Comment by legendarykamal** [comment]
Hi @eddiejaoude can I work on this ?

**Comment by eddiejaoude** [comment]
Sure, assigned to you @legendarykamal 👍

**Comment by legendarykamal** [comment]
@eddiejaoude any hints on how to dynamically render the new profiles when some new users make the profiles ?

**Comment by eddiejaoude** [comment]
I think we will need to add `createdAt` date to the Mongoose model

**Comment by Ertan222** [comment]
Maybe adding a new identifier to model like "SortThisMongooseId" will be better than date beacuse dealing with dates sometimes very hard. After that, sort by reverse going to make the job.

For dynamic page, comparison also easy "is 15 > 14? Yes, show the new user and remove the last one". But in the future maybe adding a new feature like "Member since..." is open beacuse we already have it. Idk anyone want this.

**Comment by eddiejaoude** [comment]
I think having the date of when the user joined is the most useable and flexible

**Comment by SaraJaoude** [comment]
The Discover page is quite busy at the moment already. I will close this for now.
