### ISSUE TITLE
[DOCS] Update documentation step 13.

### ISSUE THREAD

**Issue by lilmubby** [EddieHubCommunity/LinkFree#3591]
### Description

##current doc
- Click 'compare across forks' and you will see 4 drop downs
but github doesn't do this anymore

### Screenshots

![Screenshot 2023-01-17 173251](https://user-images.githubusercontent.com/103523409/212957819-62ceee5d-9714-49ab-9807-b21f06aa9674.jpg)

**Comment by Avi-88** [comment]
Hi @lilmubby , I would like to work on this. Would you mind suggesting the correct approach for this, I was thinking about changing it so that it says to choose a base repo and a base branch along with a screenshot displaying the same , like this
![image](https://user-images.githubusercontent.com/79744258/213081323-abc3271f-5664-4078-90eb-ee93a55156c1.png)

**Comment by khalidx3** [comment]
I can solve it can anyone assign it to me?

**Comment by lilmubby** [comment]
hi @Avi-88 please you can go ahead

**Comment by lilmubby** [comment]
@khalidx3 please have a look at the documentations, there's a good issue there

**Comment by Avi-88** [comment]
Hi @lilmubby  sorry for the delayed reply, I think we can just replace the current representation of the dropdowns with the actual screenshot. Please let me know what you think of this
