### ISSUE TITLE
[BUG] Viewing the new statistics page counts +1 views on profile

### ISSUE THREAD

**Issue by Balastrong** [EddieHubCommunity/LinkFree#4648]
### Description

While logged in, every time I go on the [new statistics page](https://linkfree.eddiehub.io/account/statistics), I notice the views count of my profile increases by 1.

Repro:
1. Login with GitHub
2. Find your profile on the search page (do not open it!)
3. Look at the views count
4. Open in a new tab the new statistics page
5. Go back to the tab on the search page, refresh, and search again for your profile (again, do not open it)

You will notice that the counter has increased by 1.

The repro steps are tricky but it's to avoid artificially increasing the count while reproducing the issue.

**Comment by singhmohit14072002** [comment]
- [Balastrong](https://github.com/Balastrong) 
-  I want to work on that can you please assign this task to me?

**Comment by SaraJaoude** [comment]
I am blocking this issue for the moment because when we read the profile from the API it does increment as a view. When we refactor this area with more database involvement we can look into this. 



> * [Balastrong](https://github.com/Balastrong)
> * I want to work on that can you please assign this task to me?

@singhmohit14072002 only maintainers can assign an issue.  Also, please take a look at issues which have the label `status: ready for dev`

**Comment by eddiejaoude** [comment]
This was completed in the PR https://github.com/EddieHubCommunity/LinkFree/pull/5595

**Comment by singhmohit14072002** [comment]
ok
