### ISSUE TITLE
[FEATURE] Add user profile in the Navbar

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/LinkFree#4995]
### Description

We could add the logged in user's profile in the navbar instead of them having to search their own profile 
![image](https://user-images.githubusercontent.com/51131670/220296534-78bf2322-1d28-4f2c-ad8d-3d38ccb53a83.png)

**Comment by sansarmaske** [comment]
That would be really helpful. 👍

**Comment by ChinmayMhatre** [comment]
> I will fix this issue.

Hey @ElvisJin , Maybe we could let the maintainers take a look and triage the issue then it will get assigned to you. Thank you!

**Comment by SaraJaoude** [comment]
This is a great idea. As we have the paid for Tailwind pre-built component, I will assign this to @eddiejaoude 

https://tailwindui.com/components/application-ui/navigation/navbars

**Comment by Vishrut19** [comment]
Can I work on this issue ??

**Comment by SaraJaoude** [comment]
> Can I work on this issue ??

As you can see from the conversation above this has already been assigned (and is being done as part of #5575 . Please pick an issue which has not been assigned.

**Comment by ninja-coding-man** [comment]
Sorry, I just had some accident, now I'm working on it.
Will update soon.

**Comment by SaraJaoude** [comment]
> Hey! I can't see any update from my last comment. If there is no working happening. Can I take it and try to work on it?

@Vishrut19 I replied to your comment of the 3 April on the same day.  Please read the comment history - this issue is being done as part of #5575 and therefore the two week non-activity does not apply here. 

As suggested by me a few moments ago in https://github.com/EddieHubCommunity/LinkFree/issues/6874 please look for `unassigned` issues such as: https://github.com/EddieHubCommunity/LinkFree/issues/7575.  

By spamming issues which are already assigned and people are working on, as you have done in the last few days, this is creating unnecessary notifications for maintainers as well as noise in the issue's history - we have drawn this to your attention a number of times. Any questions please ask on Discord.
