### ISSUE TITLE
fix: Incorrect Icon Used for Light Mode Theme

### ISSUE THREAD

**Issue by Saurav-Pant** [EddieHubCommunity/LinkFree#6394]
### What would you like to share?

I noticed that the website is currently displaying a moon icon in the light mode theme. While this may seem like a small detail, it can actually have a negative impact on the user experience. The moon icon is commonly associated with dark or night mode themes, while a sun icon is typically used for light mode themes.

Using the wrong icon can confuse users and make it more difficult for them to understand how to toggle between light and dark modes. I would recommend updating your light mode theme to use a sun icon instead of a moon icon. This will help ensure that users can easily identify the current mode and provide a more consistent and intuitive user experience.

https://user-images.githubusercontent.com/103263909/234738077-74345c11-a805-4427-8beb-75f96106082e.mp4

I want to work on it.

**Comment by SaraJaoude** [comment]
Thank you for this suggestion and I understand how this might be confusing.  However the icon that is displayed does not represent the mode you are on, but the alternate mode.  

We may consider adding a drop down in future in Profile settings (where the user can choose between the modes), but this would be at a later stage in the project rather than now - so I will be closing this issue.

**Comment by eddiejaoude** [comment]
I have looked at various other websites and everyone seems to do it differently. When we redesign the navigation and profile settings etc I think this can be addressed then.

Thank you for the feedback and suggestion 👍

**Comment by Saurav-Pant** [comment]
Thanks @eddiejaoude for taking this suggestion.
