### ISSUE TITLE
Slow loading time for navbar links: search, events, and map

### ISSUE THREAD

**Issue by sejosephmartin** [EddieHubCommunity/LinkFree#6419]
### Description

When clicking on the search, events, or map links in the navbar, there is a delay of approximately 1.5 or less seconds before the page loads. This issue does not occur when accessing the docs or playground links, which load quickly and smoothly.

Steps to Reproduce:
Navigate to the website
Click on the search, events, or map links in the navbar
Observe the delay in page loading time

Expected behavior: All navbar links should load quickly and without delay.

### Screenshots

https://user-images.githubusercontent.com/129386460/235110616-050f38e2-9038-41d6-aeb6-ab06aeb1c59a.mp4

**Comment by amandamartin-dev** [comment]
Related issue #6376  - perhaps a performance epic is needed?

**Comment by eddiejaoude** [comment]
Yes this pages are slow because they load all the data before displaying the page. As we move to the database usage rather the json files (from the app perspective) these page load times will improve https://github.com/EddieHubCommunity/LinkFree/issues/6244

I suggest we close this for now and revisit in the near future after the refactor
