### ISSUE TITLE
[IDEA] Profile page 3rd party widgets

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6675]
### Description

Allow people to create their own (3rd party) widgets they can use on their profile page and others can use also.

Examples:
- instead of displaying the links in a list full widget, they could be in a card on a grid
- 2 column layout with links on the left and testimonials on the right
...?

Q. How could this be implemented?

**Comment by dan-mba** [comment]
> I think the way WordPress handles widgets is pretty good. Because LinkFree is React, and React is like Lego blocks, could we build some components that could be used in these custom Widgets?

This would also expose us to the main drawback of WordPress, which is that it can be slow.

In order to pcompensate for this, most WordPress sites use CDN caching.
Right now all of LinkFree is SSR, so caching is out.

Adding a customized page design would make the serverless functions do significantly more work than fetching the data & plugging it into the components.

There are plenty of videos & blogs about using WordPress as a headless CMS and building the site with Next, Gatsby, or similar frameworks. If this is a route you think is best, I would suggest browsing a few to see the potential pitfalls of having page layouts customized by the users.

**Comment by eddiejaoude** [comment]
Thank you both for the feedback! It is great to see and learn from different perspectives

I think we will go down the route of official plugins for now, as that might be more work but also less work and security worries - so I will close this issue and when we come to do official plugins we can create a new specific issue
