### ISSUE TITLE
Bug - External URL links in the Playground builder gives 500 Internal Server Error

### ISSUE THREAD

**Issue by usmangt** [EddieHubCommunity/LinkFree#6857]
### Description

On https://linkfree.io/playground

When trying to put an external URL e.g. a medium.com or a Discourse forum link:

https://community.grafana.com/u/usmanahmad

inside the Preview either as a `links` or `socials` after successful validation. 

However, when going to that link gives 500 internal server errors.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/69509548/19eef22c-295c-446e-a4b4-b38f26a8b268)

**Comment by eddiejaoude** [comment]
Good spot, thank you 👍

**Comment by eddiejaoude** [comment]
I fixed this error in this PR https://github.com/EddieHubCommunity/LinkFree/pull/6860 but this check is required to protect profile statistics, so I will close my PR

The playground is more for a visual check rather than testing the links - we should add more info to the modal about this, we can do this in the new modal PR https://github.com/EddieHubCommunity/LinkFree/pull/6832

**Comment by eddiejaoude** [comment]
<img width="1067" alt="Screenshot 2023-05-14 at 09 53 46" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/f681f97e-db6e-40f0-97aa-8a37dfb9b3a6">
