### ISSUE TITLE
[DOCS] Add more clarity to Gitpod documentation

### ISSUE THREAD

**Issue by zaidahmad25** [EddieHubCommunity/LinkFree#7163]
### Description

Being new to contribution and open source in general, I found it a little difficult to use Gitpod to contribute to LinkFree.

I was doing a silly mistake of opening the actual repository on GitPod instead of the forked version.

Thanks to the supportive community, I was able to identify this mistake and got to make my first contribution to LinkFree 🎉

### Suggestions
Add screenshots and highlight important information to make it stand out from the documentation.

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by SaraJaoude** [comment]
> Can I work on this issue?

@munnokd we only assign one issue per person and you have already been assigned #6649. Please familiarise yourself with this project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md).  In future only request to be assigned one issue at a time  - find out if you have been assigned this issue or not before requesting another, so that you do not create confusion and unnecessary notifications for maintainers.

**Comment by eddiejaoude** [comment]
Sure @JenIsCoding I can assign it to you 👍  Being new is great, you can go through the existing docs for Gitpod and make improvements 💪 any questions let us know https://linkfree.io/docs/environments/gitpod

**Comment by JenIsCoding** [comment]
Thank you so much! I will read the GitPot doc well and I am going to think to some change to improve it. 😸

**Comment by eddiejaoude** [comment]
Great, but we don't need to replicate the Gitpod docs, we can reference it also - I think the issue was raised as it was missing some steps, for example "fork the repo first", then open with Gitpod

**Comment by JenIsCoding** [comment]
Thanks for the clarification, I didn't understand. 😅 

Maybe, we could insert a better explanation in the [Gitpod section](https://github.com/EddieHubCommunity/LinkFree#gitpod) in [Readme.md](https://github.com/EddieHubCommunity/LinkFree#readme) file? We could copy the following line:

_Be sure that you already have a fork of LinkFree in your Github Profile. If you don't have it, check out the [Quickstart Guide](https://linkfree.io/docs/quickstart)._

from the [Gitpod docs](https://linkfree.io/docs/environments/gitpod). We can add something more, if necessary. What do you think?

**Comment by GaganpreetKaurKalsi** [comment]
Hey @JenIsCoding, 
You can include whatever issues you faced while setting up LinkFree using Gitpod.

For me personally, 
I already had a LinkFree fork, but when selecting project in Gitpod, I selected the main LinkFree project instead of the forked version. This I came to know when I was trying to push the branch.

<br>

Another one, 
<img width="829" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/54144759/6c07eafb-6c3f-466e-93e9-00d099d0856c">


Prefix the url with `gitpod.io/#`. The question comes "Which URL ?". For a first time Gitpod user, this is not obvious. You can add example in this case.

**Comment by JenIsCoding** [comment]
Thanks for the suggestions, @GaganpreetKaurKalsi ❤️ 

I've just tried Gitpod to have a real experience with it, in order to understand better how to improve the documentation. 
I am currently working on the documentation's weaknesses you pointed out and on a few more 😃

**Comment by eddiejaoude** [comment]
Great collaboration 💪

**Comment by CBID2** [comment]
Hey @JenIsCoding! How’s it going with the documentation? If you need help with anything, I’m here! :)

**Comment by JenIsCoding** [comment]
Hello!
I'm preparing some screenshots to further clarify the documentation 😊 

> We have a [writing style guide](https://linkfree.io/docs/docs-style-guide) for working with documentation, so it’s best to reference this as you work on this issue.

Thanks for your link! I will make some small changes to my edits, then 😉

**Comment by JenIsCoding** [comment]
[These](https://github.com/JenIsCoding/LinkFree/blob/main/pages/docs/environments/gitpod.mdx) are, for now 😊, some improvements/changes to the Gitpod documentation.

Please, give your suggestions 😺

**Comment by CBID2** [comment]
> [These](https://github.com/JenIsCoding/LinkFree/blob/main/pages/docs/environments/gitpod.mdx) are, for now 😊, some improvements/changes to the Gitpod documentation.
> 
> Please, give your suggestions 😺

@JenIsCoding, I think it would be best to put these commits in a Pull Request. It'll make it easier for us to review your changes and ensure that it passes the automated tests. If you need help, check out my [blog post](https://chrissycodes.hashnode.dev/how-to-make-a-pull-request-without-pulling-your-hair-out) on how to create a pull request! :)
