### ISSUE TITLE
[Improvements] Fix the TODOs of api/event.js

### ISSUE THREAD

**Issue by raviraj-github** [EddieHubCommunity/LinkFree#7341]
### What would you like to share?

Creating this improvement ticket to address the outstanding task mentioned in the **api/event.js** file.

The objective is to incorporate the necessary filters into the MongoDB query and fix the TODO.

`      // TODO remove and do with mongo query
      .filter((event) => new Date(event.date.end) > new Date());`

**Comment by raviraj-github** [comment]
Can you please assign this issue to me?

**Comment by eddiejaoude** [comment]
@raviraj-github you already have an issue assigned to you, we only assign 1 issue at a time to people. Please request after the other issue assigned to you has been completed (merged), otherwise this blocks other people from contributing.

You can learn more in our contributing guide here https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by raviraj-github** [comment]
Completely Agree!

**Comment by eddiejaoude** [comment]
Thank you for understanding. I have merged your PR, so I will assign this issue to you 👍
