### ISSUE TITLE
sliding toggle them button

### ISSUE THREAD

**Issue by adarsh1215** [EddieHubCommunity/LinkFree#7528]
### Description

i want to modify the theme toggle button into into a slider

**Comment by SaraJaoude** [comment]
@adarsh1215 we are in the process of redesigning the website so I will close this issue. 

In future it would be helpful if you can explain the description the reason for raising an issue and how this benefits the project, rather than "I want to". 

As mentioned in https://github.com/EddieHubCommunity/LinkFree/pull/7474 please also refer to the [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) before contributing to the project. This will increase your chances of getting your issue accepted and assigned to you, so that you can then create a PR.
