### ISSUE TITLE
[FEATURE] Search to display 10 random profiles 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#7585]
### Description

Currently the search with no search item shows 5 random profiles, I think we could display 10

https://linkfree.io/search

Code: https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/search.js#L35
Test: https://github.com/EddieHubCommunity/LinkFree/blob/main/tests/search.spec.js#L5

**Comment by MohdTanzeel** [comment]
I want to work in this issue

**Comment by SaraJaoude** [comment]
> I want to work in this issue

@MohdTanzeel I have assigned this to you

**Comment by CS-parth** [comment]
I think I can work on this. Can this issue be assigned?

**Comment by SaraJaoude** [comment]
> I think I can work on this. Can this issue be assigned?

@CS-parth before requesting issues to be assigned to you, please check the `Assignees` box at the top of the page - this issue has been assigned to someone else. By checking before commenting this will avoid extra notifications for community members and maintainers as well. 

Here is a link to our [Contributing Guide ](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md)which you may want to take a look at so that you can see the guidelines for contributing to this project.

**Comment by SaraJaoude** [comment]
@MohdTanzeel how are you getting on?

**Comment by MohdTanzeel** [comment]
I'm getting trouble running it manually when I click on the event and search it's not giving me any search list although I made changes in.env files

**Comment by SaraJaoude** [comment]
> I'm getting trouble running it manually when I click on the event and search it's not giving me any search list although I made changes in.env files

@MohdTanzeel please take a look at the [Local Development Docs](https://linkfree.io/docs/environments/local-development) especially the note at the top of the page which will show you how to load data.
