### ISSUE TITLE
[FEATURE] Building a better landing page

### ISSUE THREAD

**Issue by devarshishimpi** [EddieHubCommunity/LinkFree#7610]
### Description

Here's the current landing page of Linkfree
![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/b394a45b-4048-4157-ad38-fb7070d68e4c)

And then comparing this with the bio.link landing page
![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/08c6fce0-a782-44ed-8876-288c4dc5d220)

Basically, the currrent landing page needs changes and be an attention grabbing one!

Example change would be fixing the color scheme, the current scheme has too much contrast
![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/9cce31c0-125d-41ac-aafc-6233512ebee4)

Another example change would be the hero section wherein it should be more of hero section showcasing linkfree, similar to what linktree/bio.link/carrd have done
![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/42457f2a-4b7e-408f-acd1-ed88d8ca34da)

**Comment by devarshishimpi** [comment]
> Thank you for your suggestion. I have labelled this issue as `discussion` as it needs to have more specific actions of what needs to be done. We also do not want this to be a copy of the bio.link page.
> 
> **Important to note:**
> 
> 1. We are going through a rebranding process at the moment so **this issue should not include any colour changes**.
> 2. We have a paid Tailwind account for this project, so any component suggestions or templates can be used (we will share the code for any agreed component): https://tailwindui.com/components

Sure! Could I probably suggest some design ideas for specific section for the rebranded version if that's fine?

**Comment by SaraJaoude** [comment]
> Sure! Could I probably suggest some design ideas for specific section for the rebranded version if that's fine?

@devarshishimpi the rebranding will take some time so in the meantime if there are any specific improvements (that do not involve colours) then please suggest them here and we can discuss these further.

**Comment by Yash-Var** [comment]
@SaraJaoude i want to work on this issue..

**Comment by SaraJaoude** [comment]
> @SaraJaoude i want to work on this issue..

@Yash-Var this issue is not ready to be worked on as it has the label `status: awaiting triage`. As you can see from the comment history and labels this is at the `talk: discussion` stage so please feel free to **suggest** any specific improvements.

I would also suggest you read through the project's [Contributing Guide](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md) so that you can familiarise yourself as to when to ask for issues to be assigned to you.

Please also avoid tagging specific maintainers - all maintainers receive notifications and can respond.  This reduces the notifications and noise for specific maintainers.

**Comment by SaraJaoude** [comment]
As rebranding has started with a design company and as this will be improved soon, I will close this issue for now.
