### ISSUE TITLE
[FEATURE] Adding A Share Section on the profile page

### ISSUE THREAD

**Issue by devarshishimpi** [EddieHubCommunity/LinkFree#7611]
### Description

Here's the current linkfree profile view

![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/35d39b2d-54f6-457f-83a8-d45e8a43fe50)
![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/0cc034a0-de52-466d-b952-f09f1d39270f)

Here's bio.link share section

![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/a1971984-0dea-4c1b-baec-f73e28ab962e)
![Screenshot by Dropbox Capture](https://github.com/EddieHubCommunity/LinkFree/assets/43378923/6c4c1530-1965-4d45-ad8e-11a5dcc393c2)

Similar share section needs to be added to linkfree.
1. Start with the copy link setting.
2. Then perhaps you could add the twitter option of sharing
3. Then maybe linkedin and the rest step-by-step

**Comment by shoebilyas123** [comment]
I suggest we can use Javascript navigator.share to implement this feature. Can I be assigned this issue please?

**Comment by SaraJaoude** [comment]
> I suggest we can use Javascript navigator.share to implement this feature. Can I be assigned this issue please?

@shoebilyas123 I have assigned this to you

**Comment by shoebilyas123** [comment]
> > I suggest we can use Javascript navigator.share to implement this feature. Can I be assigned this issue please?
> 
> @shoebilyas123 I have assigned this to you

Thank you. I'll try to raise a PR by tomorrow.

**Comment by kunalshokeen051** [comment]
Hi, everyone i have understand the issue fully and can work on it ASAP.

**Comment by SaraJaoude** [comment]
> Hi, everyone i have understand the issue fully and can work on it ASAP.

@kunalshokeen051 before requesting issues to be assigned to you, please check the Assignees box at the top of the page - this issue has been assigned to someone else. By checking before commenting this will avoid extra notifications for community members and maintainers as well.

Here is a link to our [Contributing Guide ](https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md)which you may want to take a look at so that you can see the guidelines for contributing to this project.

**Comment by shoebilyas123** [comment]
Thoughts on this share profile UI? Any suggestions for improvement?
