### ISSUE TITLE
[OTHER] <Need to add webstorm ".idea" in .gitignore>

### ISSUE THREAD

**Issue by MamunVerse** [EddieHubCommunity/LinkFree#7768]
### What would you like to share?

I suggest adding the '.idea' folder generated by JetBrains WebStorm to the project's '.gitignore' file. Many developers, including myself, use WebStorm for front-end development, and this folder contains editor-specific configuration files. By including '.idea' in '.gitignore', we can prevent these files from being uploaded to GitHub unintentionally.

### Additional information

I'd be happy to contribute. 
Please assign me.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. I strongly believe tools that are a personal preference should be added to your global git ignore not the projects, you can learn more about it here in the GitHub docs for global git ignore https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer 

So I am not keen to add more to the file, because where do we stop. I will therefore close this issue for now

**Comment by MamunVerse** [comment]
> Thank you for the suggestion. I strongly believe tools that are a personal preference should be added to your global git ignore not the projects, you can learn more about it here in the GitHub docs for global git ignore https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer 
> 
> So I am not keen to add more to the file, because where do we stop. I will therefore close this issue for now

Sorry, I don't have any idea about global git ignore before.

**Comment by eddiejaoude** [comment]
No problem. I have a YouTube short that can give you a demo https://www.youtube.com/watch?v=oH3MuD6WkZI
