### ISSUE TITLE
[BUG] options not visible

### ISSUE THREAD

**Issue by ManishBisht777** [EddieHubCommunity/LinkFree#7939]
### Description

On page - https://linkfree.io/account/manage/profile
options for layout selection are not visible due to the same color of `text` and `background` 

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/89926834/e6c711cf-59d9-43b6-8f93-12b8643f715f)

**Comment by eddiejaoude** [comment]
I can't replicate this, but as it has been raised a few times, maybe it is an issue and someone who can replicate the issue can fix

**Comment by ChinmayMhatre** [comment]
@ManishBisht777 can you mention the browser and the device you are using

**Comment by DhirajGilda** [comment]
@SaraJaoude 

I would take ownership of resolving the problem regarding the visibility of options for layout selection.

After thorough testing on both Chrome (Version 114.0.5735.199) and Brave (Version 1.52.129 Chromium: 114.0.5735.198) browsers, I can confirm that the lack of contrast between the text color and background color hinders the visibility of the layout selection options.

To address this issue, I propose adding a style attribute to the option element in the `forms/select.js` file. By modifying the code in that file, we can adjust the text color and background color to improve the contrast and enhance the visibility of the options.

I am willing to work on resolving this problem. Please assign Issue #7939 to me so that I can take the necessary steps to fix it.

Thank you for unlocking the issue, and I look forward to contributing to its resolution.

**Comment by eddiejaoude** [comment]
@DhirajGilda I have assigned it to you, thank you 👍
