### ISSUE TITLE
[FEATURE] Ability to search for language and technology that members use

### ISSUE THREAD

**Issue by mikeysan** [EddieHubCommunity/LinkFree#802]
### Description

After reading a question and answer on Discord about contributing to Python projects. It occurred to me that there is actually no way of knowing what each member is into without going through each profile. (I got distracted while typing this so let me clarify).

When I do I search for "Python", I get no responses as, rightfully, no one is called Python. However, I propose we could change/add a means to include that sort of information so that I could search for members who are into a particular language and technology.

The specific question was about contributing to python based projects. The answer was to have a look at the members as some will have python projects. Unfortunately, this is a near-impossible task as there is no simple way to check.

### Screenshots

![image](https://user-images.githubusercontent.com/13338176/145714801-476c315e-d3c9-4e18-8b47-87fbd13a7eba.png)

### Additional information

This is what gave me the idea.
![image](https://user-images.githubusercontent.com/13338176/145714975-2b145b2d-a076-4104-959d-9823180bbc1a.png)

**Comment by emmalearnscode** [comment]
Nice idea 👍

**Comment by eddiejaoude** [comment]
What about having a tags section in people's profiles that can be searched?

**Comment by Tausifqureshi786** [comment]
That sounds good, So would there be a filter dropdown on the homepage of the app which filters the profiles based on the technology tag?

**Comment by Tausifqureshi786** [comment]
I would love to work on this by the way.

**Comment by Vyvy-vi** [comment]
I'm wondering, could we have a search bar that functions like GItHub search?

**Comment by Tausifqureshi786** [comment]
If we wanna do that in order to check for the profiles with the technologies as well as the usernames then we'd have to possibly filter on two things; one profile name and second the technology(react, python, etc) in `searchHandler` at src/Components/Home/Users.js. But still the individual user data will have to be changed too.

**Comment by Vyvy-vi** [comment]
That's true...
Maybe for a preliminary version of this , we can maybe get the tags badges and fetch by tags

**Comment by JKirito** [comment]
A tag system would be beneficial as they will help filter data easily and will also help in future features development.
I think we have to change the data in /public/data/*.json as there is no correct way to determine the tech stack members use. Some have mentioned that data in their bio and in many of them it is not even present.

**Comment by mikeysan** [comment]
I like the idea of using tags. For users that do not currently use tags in their profile, we could encourage them (and new additions) to do so.

**Comment by Tausifqureshi786** [comment]
What should be the name of the property for filtering the technology in the profile. I feel that tag is a good prop and then we can ask people to add the tag and the appropriate technology to it in their profile. But how can the code be tested without having the necessary data to filter upon? Is there a testing library set up that could be used? Would appreciate some ideas.

**Comment by KendallDoesCoding** [comment]
What my comments are on this, a little different way of doing it #1070 :

In the file where users need to make their profile, they can put the languages they code in, for eg, this is what I will put in:

"languages": "HTML", "CSS", "JAVASCRIPT", "PYTHON"

Then, a button like the "Profile Type" button on the main page of Linkfree to filter out the languages and show the people that put those languages in their profile.

Idk, what the purpose of Linkfree is, if its a database or coders, contributors to EddieHubCommunity, etc. But, I'm assuming its also to get contributors to your project? If it is, then this will really be good because you can filter out the language you want help with, and contact the required people who know the coding language.

**Comment by krshkun** [comment]
We already have this as in tags I believe.

**Comment by eddiejaoude** [comment]
Thanks @krshkun yes this is done now, so I will close 👍
