### ISSUE TITLE
Select Icon from the same page search page should be displayed like a modal.

### ISSUE THREAD

**Issue by devraj4522** [EddieHubCommunity/LinkFree#8350]
### Description

Adding any icon for link and milestones edit page, currently user has to search icon from the icon page then copy the name of icon.
Then user put that name in the edit icon box. 
 
Can we enhance user experience for profile link icons by enabling icon selection within the editing page, probably by modal box from where user can select icon? 

We have already an intuitive search feature for easy icon discovery using relevant keywords. Friendly error handling guides users to correct inputs can be useful if user mistypes the icon name. This enhancements aim to streamline the process, making it effortless and error-free for users to add icons to their profile links, resulting in a more user-friendly and enjoyable platform. 

I can work on this issue too and might seek your help if necessary. 

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/55313450/2119eff1-146a-4e70-a1e5-940038824e3c)

**Comment by eddiejaoude** [comment]
Great suggestion 👍 I have assigned it to you

**Comment by devraj4522** [comment]
Thanks

**Comment by Elijah-trillionz** [comment]
Hey @devraj4522.
Thanks for pointing this out. I was suggesting instead of a modal, you could make use of an autocomplete on the input (using Headless Autocomplete component):

<img width="525" alt="linkfree-solution1" src="https://github.com/EddieHubCommunity/LinkFree/assets/60356516/9f312cdd-c1ed-4265-ba58-b14ef500a4ac">

Each item of the dropdown can display their icon as well as the title in a single line:

[s]
): Sad
(: Smiling

P.S: Just a thought

**Comment by devraj4522** [comment]
This is also a good idea, let me explore it little more.

**Comment by sital002** [comment]
@devraj4522 Do you have any update on this issue. If you don't response this issue might be assigned to someone else.

**Comment by devraj4522** [comment]
Yes, I am working on it, I was quite busy last week in one of my client project.

**Comment by devraj4522** [comment]
Pr raised #8698
