### ISSUE TITLE
[BUG] Extra top padding in doc page cards

### ISSUE THREAD

**Issue by ashmeetsmonga** [EddieHubCommunity/LinkFree#8397]
### Description

There is extra top padding in cards in doc page. We can see it when we hover over the cards. Screenshots attached for reference

### Screenshots

![Screenshot 2023-07-29 at 7 29 04 PM](https://github.com/EddieHubCommunity/LinkFree/assets/56465357/eddcae86-31cd-46b4-9268-ed312d030b0b)
![Screenshot 2023-07-29 at 7 29 17 PM](https://github.com/EddieHubCommunity/LinkFree/assets/56465357/b76aadd5-b5b1-44e6-b03c-00cf9b772b2f)

### Additional information

I would like to work on this issue if possible, thank you

**Comment by SaraJaoude** [comment]
Thank you for raising but as the rebranding has started with an agency, this will be resolved as part of this process so I will close this Issue for now.

**Comment by KSSaiTeja** [comment]
i have worked up on this issue i cant raise a pull request because i dont able to commit and push, before working on this issue i worked on another issue on this repo, so this   repo clone is already in my local machine, so after seeing this issue i started working on it, and fixed it by doing some changes. but not able to commit it.


please help me..
