### ISSUE TITLE
[BUG] Copy to clipboard in the Share to social media icons is not working

### ISSUE THREAD

**Issue by nirbhay12345** [EddieHubCommunity/LinkFree#946]
### Description

The following button is not working in the `share to social media`
 - copy to clip board

I tried clicking the button few times and it does not seem to copy the contents of the link. Instead it selects the contents of the description in the profile.

I am using BRAVE BROWSER.

At the time of this issue the linkfree is at the v0.58.3

### Screenshots

![ezgif-3-9210861ce8](https://user-images.githubusercontent.com/49341969/148681738-de805239-16fb-4c47-bb8c-c4478dd12845.gif)

**Comment by Abhi-paul16** [comment]
Hey Nirbhay , I want to work on this issue would you please assign me.

**Comment by emmalearnscode** [comment]
thanks for catching this issue. I just checked and a similar thing is happening in Chrome and it's throwing a console error.
<img width="389" alt="Screenshot 2022-01-09 155551" src="https://user-images.githubusercontent.com/57045550/148687724-c7e0c4c8-970c-4c4f-92ac-8ab80958495c.png">

**Comment by Abhi-paul16** [comment]
@emmalearnscode  can you help me in this all things working fine in development server.

**Comment by Abhi-paul16** [comment]
https://user-images.githubusercontent.com/68468264/148693853-b6a684f3-a212-4d94-a5ab-6a7f9ef5470c.mp4

**Comment by emmalearnscode** [comment]
This is going to be hard to test as it's working in development but the copy to clipboard function is async and returns a promise so I wonder if the toast should be chained inside a .then block (see the examples here: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText )

**Comment by emmalearnscode** [comment]
Hmm, I also found some information that this web API only works on https and we are currently using http so that may also be causing an issue

**Comment by Abhi-paul16** [comment]
@emmalearnscode  Thanks for sharing it and helping.

**Comment by emmalearnscode** [comment]
@eddiejaoude we have a bug in the copy to clipboard on production being caused because the site is hosted on http instead of https and the api doesn't work on http. Is upgrading to https something you are planning to do with the project?

Maybe we should comment out the copy to clipboard icon/functionality if this is not something that can be resolved at this time? Or do you have another suggestion?

**Comment by DevCassie** [comment]
> @eddiejaoude we have a bug in the copy to clipboard on production being caused because the site is hosted on http instead of https and the api doesn't work on http. Is upgrading to https something you are planning to do with the project?
> 
> Maybe we should comment out the copy to clipboard icon/functionality if this is not something that can be resolved at this time? Or do you have another suggestion?

Upgrading to https sounds like a good idea to me. If that were to happen, every link in the code (if there is any). Should be with https instead of http.

**Comment by eddiejaoude** [comment]
Thanks @emmalearnscode 👍 yes we plan to move to https, but i need some help with the Kubernetes config/setup - let me reach out to some people as i would like to do this on a live stream

**Comment by vikasganiga05** [comment]
### Description

When the copy to clipboard button is clicked it throws the error `navigator.clipboard is undefined`. I am using Firefox v95.0.2 browser. I did some [research](https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined), I found that `navigator.clipboard` is only available when the site you're browsing has a secure origin (HTTPS). [http://linkfree.eddiehub.org/](http://linkfree.eddiehub.org/) is using (HTTP). I think because of that copy to clipboard is not working.

### Screenshots

![Error Screenshot](https://user-images.githubusercontent.com/74750414/149356358-a7842489-0fc9-4907-b74e-d3b096933dda.png)



### Additional information

My suggestion is to use old-school copy to clipboard using the [out of viewport hidden textarea trick](https://stackoverflow.com/a/60292243).
```js
const CopyLink = () => {
  if (typeof(navigator.clipboard) == 'undefined') {
    // Do the out of viewport hidden textarea trick.
  }
  navigator.clipboard.writeText(`http://linkfree.eddiehub.org/${username}`)
  toast.current.show({
    severity: 'success',
    summary: 'Link copied to clipboard.',
  })
}
```

**Comment by nirbhay12345** [comment]
> My suggestion is to use old-school copy to clipboard using the out of viewport hidden textarea trick.

I think for the time being this could be a helpful solution. Since it prevents the broken site. 

Further this bug can be removed as mentioned by @eddiejaoude 

What are others views?
@emmalearnscode

**Comment by emmalearnscode** [comment]
My concern with adding the workaround is that it's not acutally possible to test it in development as the copy to clipboard is working on localhost. Therefore, we won't know if it works until pushing to production. Then when we finally do upgrade to https, there will be unnecessary code which we might forget to remove. My feeling would be to comment out the sharing link and just leave the three working social sharing links visible for now until Eddie has time to upgrade. Curious to see what others think.

**Comment by nirbhay12345** [comment]
>  Therefore, we won't know if it works until pushing to production. Then when we finally do upgrade to https, there will be unnecessary code which we might forget to remove

Yeah I did not thought of this. This might turn out to be an overhead later. I agree that it should be commented.

**Comment by KendallDoesCoding** [comment]
For now, till this issue gets resolved, maybe remove the copy to clipboard icon?

**Comment by eddiejaoude** [comment]
https has now been added to the LinkFree project and I just tested the copy link and it works 🎉 

Thank you all for the great collaboration 🔥
